# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: test core

on:
  push:
    branches:
      - dev
      - 1.x
  pull_request:
    paths:
      - '.github/workflows/test-core.yml'
      - 'core/**'
      - '!core/tauri/scripts/**'

env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              toolchain: '1.65.0',
              cross: false,
              command: 'test'
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              toolchain: '1.65.0',
              cross: false,
              command: 'test'
            }
          - {
              target: x86_64-apple-darwin,
              os: macos-latest,
              toolchain: '1.65.0',
              cross: false,
              command: 'test'
            }
          - {
              target: aarch64-apple-ios,
              os: macos-latest,
              toolchain: '1.65.0',
              cross: false,
              command: 'build'
            }
          - {
              target: aarch64-linux-android,
              os: ubuntu-latest,
              toolchain: '1.65.0',
              cross: true,
              command: 'build'
            }
        features:
          - {
              args: --no-default-features,
              key: no-default
            }
          - {
              args: --features compression,wry,linux-ipc-protocol,isolation,custom-protocol,tray-icon,test,
              key: all
            }

    steps:
      - uses: actions/checkout@v4

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.platform.toolchain }}
          target: ${{ matrix.platform.target }}
          override: true
          default: true

      - name: install Linux dependencies
        if: contains(matrix.platform.target, 'unknown-linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libayatana-appindicator3-dev

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: core -> ../target
          save-if: ${{ matrix.features.key == 'all' }}

      - name: Downgrade crates with MSRV conflict
        # The --precise flag can only be used once per invocation.
        run: |
          cargo update -p time --precise 0.3.23
          cargo update -p toml@0.7.8 --precise 0.7.6
          cargo update -p toml_edit@0.19.15 --precise 0.19.14
          cargo update -p cfg-expr@0.15.5 --precise 0.15.4
          cargo update -p system-deps --precise 6.1.1

      - name: test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.platform.cross }}
          command: ${{ matrix.platform.command }}
          args: --target ${{ matrix.platform.target }} ${{ matrix.features.args }}
